alerts:
- rule: DEPLOYMENT_FAILED
domains:
- domain: app.moclojer.com
  type: PRIMARY
name: moclojer-app
services:
- name: front
  dockerfile_path: docker/Dockerfile.front
  envs:
  - key: API_URL
    scope: RUN_TIME
    value: https://
- name: api
  dockerfile_path: docker/Dockerfile.api
  envs:
  - key: DATABASE_URL 
    scope: RUN_TIME
    value: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_TIME
    value: "foo"
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_TIME
    value: "bar"
  - key: REDIS_DATABASE
    scope: RUN_TIME
    value: "redis://localhost:6379"
  - key: PROFILE
    scope: RUN_TIME
    value: "prod"
- name: yaml-generator
  dockerfile_path: docker/Dockerfile.yaml-generator
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_TIME
    value: "foo"
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_TIME
    value: "bar"
  - key: REDIS_DATABASE
    scope: RUN_TIME
    value: "redis://localhost:6379"
  - key: PROFILE
    scope: RUN_TIME
    value: "prod"
