version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.cc
      PGADMIN_DEFAULT_PASSWORD: pg
    ports:
      - "5433:80"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis

  # https://docs.localstack.cloud/user-guide/aws/s3/#s3-docker-image
  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566" # Gateway      
    environment:
      - AWS_ACCESS_KEY_ID="foo"
      - AWS_SECRET_ACCESS_KEY="bar"
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=${DEBUG:-1}
    volumes:
      - "${LOCALSTACK_DIR:-./localstack}:/var/lib/localstack"

volumes:
    db-data:
