version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.cc
      PGADMIN_DEFAULT_PASSWORD: pg
    ports:
      - "5433:80"

  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass redislocal"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis

  #localstack to test bucket code
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
      - "8080:8080" # dashboard

volumes:
    db-data:
