FROM clojure:latest

RUN apt-get update
RUN apt-get -y install git-core
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_18.x   | bash -
RUN apt-get -y install nodejs

WORKDIR /app
COPY . .

ENV DEBUG=false

RUN npm i . && \
    npm run postinstall && \
    npm run release

ENV API_URL $API_URL
EXPOSE 8000

