version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.cc
      PGADMIN_DEFAULT_PASSWORD: pg
    ports:
      - "5433:80"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis

  #localstack to test bucket code
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4583:4566-4583"
    environment:
      - SERVICES=s3,lambda,sqs,apigateway,cloudformation
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
    volumes:
      - "./.localstack:/localstack"

volumes:
    db-data:
