CREATE TABLE IF NOT EXISTS file (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  content TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
