CREATE TABLE IF NOT EXISTS mock (
  id uuid NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  org VARCHAR(255) NOT NULL,
  subdomain VARCHAR(255) NOT NULL,
  content TEXT NULL,
  published BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
