CREATE TABLE IF NOT EXISTS mock (
  id uuid NOT NULL PRIMARY KEY,
  org_id uuid NULL,
  user_id uuid NULL,
  subdomain VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
