name: Sentry SourceMaps

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubunt-latest
    steps:
    - name: Ensure sourcemaps formatting
      run: sed -i 's/sourceMappingURL=/sourceMappingURL=https:\/\/app.moclojer.com\/assets\/js\//g' -r resources/front/public/js/core.js.map

    - name: Upload to Sentry
      uses: getsentry/action-release@v1.0.0
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: moclojer
        SENTRY_PROJECT: moclojer-app-front
      with:
        environment: prod
        version: 1.0
        sourcemaps: resources/public/js/core.js.map
