name: Tests Backend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'src/back/**'
      - 'src/components/**'
      - 'test/back/back/api/integration/api/**'
      - 'resources/back/**'
      - 'src/yaml_generator/**'
      - 'src/components/**'
      - 'test/back/back/yml_generator/**'
      - 'resources/back/**'
      - 'src/moclojer/**'
      - 'src/components/**'
      - 'test/back/back/moclojer/**'
      - 'resources/back/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tests:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1273

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 7
      - name: Start localstack
        run: |
          pip install localstack awscli-local[ver1] # install LocalStack cli and awslocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out 
          echo "Startup complete"          ck

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'src/back/**'
              - 'src/components/**'
              - 'test/back/back/api/integration/api/**'
              - 'resources/back/**'
            yaml-generator:
              - 'src/yaml_generator/**'
              - 'src/components/**'
              - 'test/back/back/yml_generator/**'
              - 'resources/back/**'
            moclojer:
              - 'src/moclojer/**'
              - 'src/components/**'
              - 'test/back/back/moclojer/**'
              - 'resources/back/**'

      - name: Test API
        if: steps.filter.outputs.api == 'true'
        run: clojure -M:test api

      - name: Test Yaml Generator
        if: steps.filter.outputs.yaml-generator == 'true'
        run: clojure -M:test yaml-generator

      - name: Test Moclojer Lib
        if: steps.filter.outputs.moclojer == 'true'
        run: clojure -M:test moclojer
